// Code generated by "stringer -type=HTTPMethod"; DO NOT EDIT

package generator

import "fmt"

const _HTTPMethod_name = "GETPOSTPUTPATCHDELETE"

var _HTTPMethod_index = [...]uint8{0, 3, 7, 10, 15, 21}

func (i HTTPMethod) String() string {
	if i < 0 || i >= HTTPMethod(len(_HTTPMethod_index)-1) {
		return fmt.Sprintf("HTTPMethod(%d)", i)
	}
	return _HTTPMethod_name[_HTTPMethod_index[i]:_HTTPMethod_index[i+1]]
}
